### ISSUE TITLE
 unable to authenticate, attempted methods [none password], no supported 

### ISSUE THREAD

**Issue by cforcross** [appleboy/ssh-action#141] opened 2021-10-28 20:33 UTC
I been getting the error below all day would really appreciate some help ..thanks 👇🏿👇🏿👇🏿

/usr/bin/docker run --name f8842016b92d296e4946eba248b04a6cfde9c4_ebfb96 --label f88420 --workdir /github/workspace --rm -e INPUT_HOST -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_PORT -e INPUT_SCRIPT -e INPUT_PASSPHRASE -e INPUT_SYNC -e INPUT_USE_INSECURE_CIPHER -e INPUT_CIPHER -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY -e INPUT_KEY_PATH -e INPUT_FINGERPRINT -e INPUT_PROXY_HOST -e INPUT_PROXY_PORT -e INPUT_PROXY_USERNAME -e INPUT_PROXY_PASSWORD -e INPUT_PROXY_PASSPHRASE -e INPUT_PROXY_TIMEOUT -e INPUT_PROXY_KEY -e INPUT_PROXY_KEY_PATH -e INPUT_PROXY_FINGERPRINT -e INPUT_PROXY_CIPHER -e INPUT_PROXY_USE_INSECURE_CIPHER -e INPUT_SCRIPT_STOP -e INPUT_ENVS -e INPUT_DEBUG -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true --network github_network_989a05f727fa403a98a9ad9475126b7c -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/ridepudo/ridepudo":"/github/workspace" f88420:16b92d296e4946eba248b04a6cfde9c4
======CMD======
cd /home/ridepudo/public_html/stage/ridepudo
git checkout -f 
sudo git pull 

======END======
2021/10/28 20:26:43 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

**Comment by iamsail** [comment] 2021-11-07 13:49
i get this error too, how resolve it

**Comment by iamsail** [comment] 2021-11-12 02:57
@cforcross 
I resolve it. Because my config host is accidentally mismatched， then I changed my host config , it can work.
you can check your config and try.

**Comment by YakovL** [comment] 2022-01-25 08:00
yeah, would be nice to have a more helpful debug message, not sure how trace the source of the problem yet

**Comment by YakovL** [comment] 2022-01-25 08:02
looks like this is a duplicate of #80 though, more discussion there

**Comment by abdellatif-hassani** [comment] 2024-04-22 19:03
I had the same error and I resolve it by changing : 

  - name: Deploy to server
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker image pull my-image
            ....
            
            
  By : 
  
  - name: Deploy to server
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker image pull my-image
            ....
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          
 I hope that help you.

**Comment by appleboy** [comment] 2024-05-04 11:58
@cforcross Please try the latest version and re-open the issue if you still encounter the same problem.

**Closed by appleboy** 2024-05-04 11:58 UTC

**Comment by appleboy** [comment] 2025-04-26 15:50
Please try the following config:

```yaml
use_insecure_cipher: true
```
